#!/usr/bin/env bash
# This script installs a load balancer haproxy and configures it

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy
sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 37340-web-01 100.24.237.155 check\n\tserver 37340-web-02 100.26.168.221 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
