#!/usr/bin/env bash
#Using a while loop to display the content of the file /etc/passwd
# Script should display:
# - username
# - user id
# - Home directory path for the user

while read -r passwd
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
