#!/usr/bin/env bash
# This script uses while loop to display the time for:
# - 12 hours and 59 minutes

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=0
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
