#!/usr/bin/env bash
# Using a for loop to display:
# - The content of the current directory
# - In a list format
# - Where only the part of the name after the first dash is displayed

for input in *
do
	echo "$input" | cut -f 2- -d '-'
done
