#!/usr/bin/env bash
#Configuring Ubuntu server with the specific new server requirements as follows:
# - localhost rsolves to 127.0.0.2
# - facebook.com resolves ti 8.8.8.8

sudo cp /etc/hosts ~hosts.bak
sudo sed -i 's/^127\.0\.0\.1\s*localhost/127.0.0.2\tlocalhost/' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts
sudo systemctl restart networking
