#!/usr/bin/env bash
#Configuring Ubuntu server with the specific new server requirements as follows:
# - localhost rsolves to 127.0.0.2
# - facebook.com resolves ti 8.8.8.8

sudo cp /etc/hosts ~hosts.bak
echo '127.0.0.2 localhost' | sudo tee -a /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts

if [ -f /.dockerenv ]; then
    sudo service docker restart
fi
