#!/usr/bin/env bash
#Configuring Ubuntu server with the specific new server requirements

#Backing up original host files
sudo cp /etc/hosts /etc/hosts.bak

#Replacing the default server entry with 127.0.0.2
sudo sed -i 's/^127\.0\.0\.1\s*localhost/127.0.0.2\tlocalhost/' /etc/hosts

#Adding up an entry for facebook.com that resolves to 8.8.8.8
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts
